import type { OnboardingPreferences } from "./types";

export type Persona = {
  id: string;
  name: string;
  tagline: string;
  avatar: string;
  avatarBg: string;
  onboardingComplete: boolean;
  profileData: OnboardingPreferences;
};

export const DEFAULT_PERSONAS: Persona[] = [
  {
    id: "maja",
    name: "Maja Hoffmann",
    tagline: "Frequent business traveller · BahnCard 50",
    avatar: "MH",
    avatarBg: "#ec0016",
    onboardingComplete: false,
    profileData: {
      personal: {
        full_name: "Maja Hoffmann",
        employment_status: "employed",
        profession: "Consultant",
        household_context: "single",
      },
      location: { home_city: "Köln" },
      commute: {
        office_days: ["mon", "tue", "wed", "thu"],
        wfh_days: ["fri"],
      },
      car: {
        owns_car: false,
        fuel_type: null,
        car_size: null,
        efficiency: null,
        efficiency_unit: null,
        monthly_km_estimate: null,
      },
      subscriptions: [
        {
          id: "bahncard50",
          category: "rail_subscription",
          cost_structure: "fixed_annual_discount",
          provider: "Deutsche Bahn",
          product: "BahnCard 50",
          monthly_cost_eur: 20.33,
          billing_cycle: "annual",
          next_renewal_date: "2025-12-31",
          started: "2024-01-01",
          coverage_scope: "Germany nationwide",
          notes: "",
          annual_price: 244,
          discount_rate: 50,
          travel_class: "2nd",
        },
      ],
      priorities: { cost: 0.54, time: 0.16, sustainability: 0.3 },
      integrations: {
        outlook_connected: true,
        gmail_connected: false,
        calendar_connected: false,
        db_connected: true,
        miles_connected: true,
        deutschlandticket_connected: true,
        additional_connections: ["KVB", "RMV", "FreeNow"],
      },
      notes: "Mostly travel Cologne–Frankfurt, sometimes Hamburg.",
    },
  },
  {
    id: "stefan",
    name: "Stefan Kurz",
    tagline: "Car owner · Occasional train traveller",
    avatar: "SK",
    avatarBg: "#1f6feb",
    onboardingComplete: false,
    profileData: {
      personal: {
        full_name: "Stefan Kurz",
        employment_status: "employed",
        profession: "Engineer",
        household_context: "partner",
      },
      location: { home_city: "München" },
      commute: {
        office_days: ["mon", "tue", "wed", "thu", "fri"],
        wfh_days: [],
      },
      car: {
        owns_car: true,
        fuel_type: "Petrol",
        car_size: "Medium car",
        efficiency: 7.5,
        efficiency_unit: "L/100km",
        monthly_km_estimate: 600,
      },
      subscriptions: [
        {
          id: "stefan-bc50",
          category: "rail_subscription",
          cost_structure: "fixed_annual_discount",
          provider: "Deutsche Bahn",
          product: "BahnCard 50 (2. Klasse)",
          monthly_cost_eur: 20.33,
          billing_cycle: "annual",
          next_renewal_date: "2027-01-15",
          started: "2024-01-15",
          coverage_scope: "Germany nationwide",
          notes: "Annual card at €244/yr, auto-renews January. 50% discount on all DB long-distance fares.",
          annual_price: 244,
          discount_rate: 50,
          travel_class: "2nd",
        },
        {
          id: "stefan-dticket",
          category: "rail_subscription",
          cost_structure: "fixed_recurring",
          provider: "Deutschlandticket",
          product: "Deutschland-Ticket",
          monthly_cost_eur: 58,
          billing_cycle: "monthly",
          next_renewal_date: "2026-07-01",
          started: "2023-05-01",
          coverage_scope: "Germany nationwide",
          notes: "Unlimited travel on all local and regional public transport across Germany. Monthly, cancellable.",
        },
        {
          id: "stefan-miles",
          category: "carsharing",
          cost_structure: "usage_membership",
          provider: "MILES Mobility",
          product: "MILES+ Abo",
          monthly_cost_eur: 4.90,
          billing_cycle: "monthly",
          next_renewal_date: "2026-07-01",
          started: "2022-06-15",
          coverage_scope: "",
          notes: "Car-sharing membership tier. Provides 5% cashback on MILES trip costs and slightly reduced per-minute rate.",
          monthly_fee: 4.90,
        },
      ],
      priorities: { cost: 0.3, time: 0.5, sustainability: 0.2 },
      integrations: {
        outlook_connected: false,
        gmail_connected: true,
        calendar_connected: true,
        db_connected: true,
        miles_connected: true,
        deutschlandticket_connected: true,
        additional_connections: ["MVV", "Bolt"],
      },
      notes: "Drive to work daily within Munich. Regular business trips to Frankfurt by train (company HQ is in Frankfurt-Sachsenhausen).",
    },
  },
  {
    id: "lena",
    name: "Lena Brandt",
    tagline: "Student · Deutschlandticket",
    avatar: "LB",
    avatarBg: "#1a7f37",
    onboardingComplete: false,
    profileData: {
      personal: {
        full_name: "Lena Brandt",
        employment_status: "student",
        profession: "Student",
        household_context: "single",
      },
      location: { home_city: "Hamburg" },
      commute: {
        office_days: ["mon", "tue", "wed", "thu"],
        wfh_days: ["fri"],
      },
      car: {
        owns_car: false,
        fuel_type: null,
        car_size: null,
        efficiency: null,
        efficiency_unit: null,
        monthly_km_estimate: null,
      },
      subscriptions: [
        {
          id: "lena-bc50",
          category: "rail_subscription",
          cost_structure: "fixed_annual_discount",
          provider: "Deutsche Bahn",
          product: "BahnCard 50 (2. Klasse)",
          monthly_cost_eur: 20.33,
          billing_cycle: "annual",
          next_renewal_date: "2027-01-15",
          started: "2023-01-15",
          coverage_scope: "Germany nationwide",
          notes: "Annual card at €244/yr, auto-renews January. 50% discount on all DB long-distance fares.",
          annual_price: 244,
          discount_rate: 50,
          travel_class: "2nd",
        },
        {
          id: "dt",
          category: "rail_subscription",
          cost_structure: "fixed_recurring",
          provider: "HVV",
          product: "Deutschlandticket",
          monthly_cost_eur: 49,
          billing_cycle: "monthly",
          next_renewal_date: "2026-08-01",
          started: "2023-05-01",
          coverage_scope: "Germany nationwide",
          notes: "",
        },
      ],
      priorities: { cost: 0.5, time: 0.2, sustainability: 0.3 },
      integrations: {
        outlook_connected: false,
        gmail_connected: true,
        calendar_connected: false,
        db_connected: true,
        miles_connected: false,
        deutschlandticket_connected: true,
        additional_connections: ["HVV", "Nextbike"],
      },
      notes: "Commute to university by U-Bahn and S-Bahn.",
    },
  },
];
